name: Change Repository Topics

on:
  workflow_dispatch: #Manually trigger via GitHub
    inputs:
      topics:
        description: 'Comma-separated list of topics to add'
        required: true
        default: 'rpg,javascript,game,text-adventure,browser-game,html,css,interactive-fiction,adventure,singleplayer,role-playing-game'

jobs:
  update-repo-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Update Topics
        uses: actions/github-script@v7.1.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            try {
              const topics = inputs.topics.split(',').map(t => t.trim());
              await github.request('PATCH /repos/{owner}/{repo}/topics', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                names: topics,
                headers: { 'Accept': 'application/vnd.github+json' }
              });
              console.log('Successfully updated topics:', topics);
            } catch (error) {
              core.setFailed(`Failed to update topics: ${error.message}`);
            }
