name: Add Topics

on:
  workflow_dispatch: # Manually trigger via GitHub

jobs:
  add-topics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.request('PATCH /repos/{owner}/{repo}/topics', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              names: [
                "rpg",
                "javascript",
                "game",
                "text-adventure",
                "browser-game",
                "html",
                "css",
                "interactive-fiction",
                "adventure",
                "singleplayer",
                "role-playing-game"
              ],
              headers: { 'Accept': 'application/vnd.github.mercy-preview+json' }
            });
